all : recommandserver.bin recommandclient.bin

recommandserver.bin : recommandserver.c 
	gcc -o recommandserver.bin recommandserver.c 

recommandclient.bin : recommandclient.c
	gcc -o recommandclient.bin recommandclient.c 